### ISSUE TITLE
Alpha version bump

### ISSUE THREAD

**Issue by ppiotrow** [fthomas/scala-steward#1003]
The Scala Steward bumps versions of the stable artefacts to alpha. This version is most likely not recommended or in case of Netty very old. Should this be handled by Steward as a special case?
```
org.eclipse.jetty:{jetty-client, jetty-server} : 9.3.11.v20160721 -> 9.3.27.v20190418 -> 9.4.20.v20190813 -> 10.0.0-alpha0
io.netty:netty-codec-http2 : netty-4.1.42.Final -> 5.0.0.Alpha2
```
<img width="606" alt="Screenshot 2019-09-27 at 08 51 02" src="https://user-images.githubusercontent.com/3899229/65749920-7c6c3e00-e107-11e9-8522-44eb447a665f.png">

Wonderful project, just implemented in the company's private repo, thanks :)

**Comment by fthomas** [comment]
Thanks for the report, @ppiotrow! You're right, Scala Steward should not propose an update from a stable version to a newer alpha or beta version for the same reason as outlined in #956. This will be fixed with #1015.
