### ISSUE TITLE
Steward stalled during scalafix migration

### ISSUE THREAD

**Issue by exoego** [fthomas/scala-steward#1005]
My private Steward produces no output for long time during scalafix migration for scalacheck over a my company project.

```
2019-09-28 09:37:18,257 INFO  Process update org.scalacheck:scalacheck:test : 1.14.0 -> 1.14.2
2019-09-28 09:37:18,383 INFO  Applying migrations: NonEmptyList(Migration(org.scalacheck,NonEmptyList(scalacheck),Version(1.14.1),NonEmptyList(github:typelevel/scalacheck/v1_14_1?sha=3fc537dde9d8fdf951503a8d8b027a568d52d055)))
// stalled here
```

My infastrcture for Steward watches a process and kill if the process seems stall (no output for 10 minutes).
I can loose this limitation, but I think this might be an issue for other people.

If I run the same scalafix on my PC, it finishes without error for several minutes.
So I think Steward also can finish compile and scalafix if it do not stall.

So I think it would be benefical if Steward periodically (like 1 minute) print `.` or something durinig time-consuming command like `scalafix`

**Comment by tigertiger123** [comment]
بتاريخ السبت، 28 سبتمبر 2019، جاء من TATSUNO Yasuhiro <
notifications@github.com>:

**Comment by exoego** [comment]
Closing since periodic logging introduce non-essential complexity to Steward.
It should be addressed in runtime infrastructure.

**Comment by fthomas** [comment]
I'd like to add two notes here. I also experienced hanging Scalafix migrations and added a timeout for running processes to mitigate this problem (see #764 and #776). The second is that Scala Steward can print sbt's output while it is running using the `TRACE` log level. I guess it would help in your situation but it would also clutter your log files. :-)
