### ISSUE TITLE
Propose sbt updates

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#101]
Scala steward should also propose sbt updates and not only library and plugin upates.

**Comment by jhnsmth** [comment]
I'd like to volunteer myself for this feature if no one else is already working on it

**Comment by fthomas** [comment]
I'm not aware of anyone else who is working on this, so go for it!

**Comment by jhnsmth** [comment]
Thanks for the quick answer. I will give it a try during next week.
