### ISSUE TITLE
Remove "keepCredentials" and "setCredentialsToNil"

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1022]
In 0b7d6c6a07c3610ca3fb08cd6ec6a0beef49d5a1 we unset sbt `credentials` so that sbt-updates could find updates when this is set but the underlying credential file is not present. In #253 we then introduced the `--keep-credentials` option to configure whether the credentials setting is changed or not. I think both aren't necessary anymore with sbt-updates 0.4.3 which includes a fix for https://github.com/rtimush/sbt-updates/issues/123.

**Comment by manuelcueto** [comment]
Looking into it
