### ISSUE TITLE
Suggest updates for Scalafix dependencies

### ISSUE THREAD

**Issue by mwz** [fthomas/scala-steward#1032]
It would be fantastic if Scala Steward could also suggest updates for `scalafixDependencies` the same way it does for `libraryDependencies`.

Is that something that would need to be implemented in the sbt-updates plugin or could it be done directly in Scala Steward?

**Comment by fthomas** [comment]
I think it could be done directly in Scala Steward by the same mechanism that is used for sbt updates. (By adding `scalafixDependencies` temporarily as `libraryDependencies`.) But then only Scala Steward users would benefit from that. If sbt-updates would report updates for `scalafixDependencies`, a lot more people would benefit from it.

**Comment by fthomas** [comment]
We're slowly moving in the direction of using Coursier instead of sbt-updates for finding updates. The primary reason for this move is performance because Coursier allows us find updates without running sbt for each project. So this feature needs to be implemented in Scala Steward directly.
