### ISSUE TITLE
Flag to Disable Scalafix in Execution

### ISSUE THREAD

**Issue by Raimmaster** [fthomas/scala-steward#1043]
Some of the scalafix migrations take quite a while in the pipeline when there are many repos. For some cases we don't need them to be ran, we just need to check dependencies and wait for the test suite to let us know about the behavior, e.g. when testing locally.

Perhaps adding a flag to when steward is to be run, e.g. `--scalafix-disable`, would be helpful.

**Comment by fthomas** [comment]
Instead of another flag, we could also stop hardcoding the available Scalafix migrations and move them into an external file where users could easily add their own or remove pre-defined migrations. Disabling Scalafix completely can then be achieved by removing all migrations from this file.

**Comment by manuelcueto** [comment]
Should the file be in the repo? or something passed to Scala-steward when run? I.e a global scalafix configuration.
