### ISSUE TITLE
Limit number of updates

### ISSUE THREAD

**Issue by redkhalil** [fthomas/scala-steward#1046]
Is there any way to limit the number of updates that happen?
In my use case, for each update we have 2 builds (push and PR). For N updates, that would result in 2N builds. I would like to be able to configure a limit so that I can have 1-2 updates for a run. Reasons are:
- This prevents flooding of our CI
- We run Steward daily, so by limiting the updates we can amortize the effort that goes into maintaining the repos.
- When build.sbt gets updated (following a merge to master), we need to resolve conflict and then merge the resolution. So that's another 2 builds. And we have to repeat this for each PR. Therefore I conclude that it's not worthwhile to have N updates in a day, I'd rather spread this over several days.

**Comment by fthomas** [comment]
There is currently no way to limit the number of PRs that are created but it sounds like a sensible feature to me. I think it should be configurable via `.scala-steward.conf`.
