### ISSUE TITLE
Google Contributor License Agreement (CLA)

### ISSUE THREAD

**Issue by Sebruck** [fthomas/scala-steward#1053]
Hi

I am the maintainer of https://github.com/census-ecosystem/opencensus-scala which lives in the census-ecosystem organisation which is owned and managed by google. I would love to use the scala-steward in this project, however to contribute to any google open source projects it is a requirement to sign their Contributor License Agreement (CLA) .

Would it be possible for you to do that with the scala-steward account?

The CLA can be signed here: https://cla.developers.google.com/clas
Example PR: https://github.com/census-ecosystem/opencensus-scala/pull/89

Thanks a lot!!

**Comment by fthomas** [comment]
Ok, signed it. I've signed other CLAs as @scala-steward before but this was the most inconvenient experience so far because it required creating a Google account for Scala Steward.

**Comment by Sebruck** [comment]
@fthomas I totally forgot to thank you for your effort!  Thanks a lot ❤️

**Comment by fthomas** [comment]
You're welcome! And sorry for venting about Google's CLA signing process. My frustration wasn't directed at you -- I just felt that the process was unnecessary cumbersome and apparently it needed to be said. :-)
