### ISSUE TITLE
Apply updates with Scalafix migration last

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1065]
Updates that involve Scalafix migrations sometimes fail. If there are multiple updates for one repo and the first one Scala Steward applies fails because a Scalafix migration fails, other updates are not applied. To apply as much updates as possible, updates that involve Scalafix migrations should be applied last.

**Comment by manuelcueto** [comment]
One approach could be to sort the updates  in nurtureAlg after grouping them, putting the ones with migrations in the end. WDYT?

**Comment by fthomas** [comment]
That sounds good.
