### ISSUE TITLE
Do not use non-browsable URLs as links in the PR body

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1071]
As happened in https://github.com/mfirry/scala-http-clients/pull/76 with SCM URL `git@github.com/playframework/play-ws.git`. We're extracting this URL from the [POM](https://repo1.maven.org/maven2/com/typesafe/play/play-ws-standalone-json_2.12/2.1.0-M7/play-ws-standalone-json_2.12-2.1.0-M7.pom). I'd suggest to fall back to the homepage if the scm.url is not suitable as link.

**Comment by manuelcueto** [comment]
Couldn't you strip `git@` and `.git` from that url?

**Comment by mwz** [comment]
> Couldn't you strip `git@` and `.git` from that url?

You can navigate to github.com/playframework/play-ws.git, so it's just the prefix `git@` that would need to be stripped to make this URL "browsable".

**Comment by fthomas** [comment]
GitHub's "Clone or download" buttons contain `git@`-URLs like this one `git@github.com:fthomas/scala-steward.git` (note the semicolon). If people would use these as SCM URLs and we would only remove the `git@` prefix, we still don't get browsable URLs.

I'd prefer to keep it simple and just fall back to the homepage if the SCM URL starts with `git@`.

**Comment by manuelcueto** [comment]
Forgive my ignorance, but what do you mean by homepage? do you mean github.com?

**Comment by fthomas** [comment]
Sorry, I should have been more precise. [`CoursierAlg.getArtifactUrl`](https://github.com/fthomas/scala-steward/blob/83f0d1a557792bfa294f96136ab9e19109f3579d/modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala#L63-L66) extracts the homepage and SCM URL from the POM. If the SCM URL is not defined it returns the homepage. I suggest to also fall back to the homepage if the SCM URL is defined but begins with `git@`.
