### ISSUE TITLE
Stop updating repos that have more than n open PRs

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#108]
If a repository has more than `n` (say 30) open pull requests by Scala steward it makes sense to ignore this repository until the open PR count drops below the threshold `n`. Many open pull requests are a sign that a repository is abandoned and working on that is just a waste of resources.

**Comment by manuzhang** [comment]
Or just keep ONE PR for the same dependency

**Comment by fthomas** [comment]
Right now there are only two repos that have a lot of open pull requests by Scala Steward, so this is not a top priority for me right now.

The "one PR per dependency" feature is tracked in #418.
