### ISSUE TITLE
Set a Gravatar for the scala-steward user

### ISSUE THREAD

**Issue by aeons** [fthomas/scala-steward#111]
GUI git clients that show gravatars for commits would look even better with a [Gravatar](https://en.gravatar.com/) for scala-steward :)

**Comment by fthomas** [comment]
Just set a Gravatar for scala-steward. @aeons could you check if it works for you?

**Comment by aeons** [comment]
Yep, looks great :)
<img width="399" alt="image" src="https://user-images.githubusercontent.com/1432894/47845792-3d821b00-ddc6-11e8-91ca-80a802f1e068.png">

Thanks!
