### ISSUE TITLE
Check user permission for repos to fail-fast

### ISSUE THREAD

**Issue by manuelcueto** [fthomas/scala-steward#1110]
Using this api [api.github](https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level) we could check if scala-steward (or whatever user it is being used) has at least write access before starting to look for updates, effectively speeding up runs. This would work in combination with `--do-not-fork` runs.

**Comment by fthomas** [comment]
If it has no write access, this a configuration error in either Scala Steward or in the repo, right? So if it happens, someone will correct it and it only speed up runs in case there is a configuration error. Do I get that right?

**Comment by manuelcueto** [comment]
Well in our use case our list of repos is provided and some of those repos haven't allowed write access to our scala-steward username, and because it belongs to the organization, it has read access to all of them. Given it's about 25/30 repos that provide no write access, we see that it takes around 5/6 minutes to create update branches for each repo before finding out that Scala-steward cannot push those prs and move on to the next repo. of course we'd be happy to filter those repos with github's api to find out the right ones and write them to a new file before running steward, but i thought it would maybe be an interest feature to suggest.
Let me know what your thoughts are, otherwise we can close this issue.

**Comment by fthomas** [comment]
But after running steward, you change the repos to give write access to your steward user, right? Or you remove the repos from `repos.md` if you don't like to give the user write access to them. So I only see a speedup in the error case and I'm hesitant to optimize that if there is still so much potential to make the happy path faster.

Does that make sense or am I still missing something?

**Comment by fthomas** [comment]
I'm going to close this mainly because I don't think Scala Steward is mature enough to optimize the unhappy paths.
