### ISSUE TITLE
Replace SbtAlg.getUpdatesForProject with coursier.Versions()

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1126]
Coursier recently added an API to list versions of a module, see https://github.com/coursier/coursier/pull/1439. It seems to me that this could be used to replace `SbtAlg.getUpdatesForProject` which we're currently using to find updates of all dependencies Scala Steward knows about in order to decide on which repos it should work on. In `getUpdatesForProject` we're writing modules to an artificial sbt project that we then load with sbt and where we call sbt-update's task to find new versions. It seems to me that the new Coursier API allows us to find new versions without executing sbt. And since executing sbt is really slow, this change could make Scala Steward a lot faster (at least if `--prune-repos=true`).

**Comment by manuelcueto** [comment]
I Will start taking a look at it if everybody's ok with it :)

**Comment by fthomas** [comment]
Go for it! :-)

**Comment by fthomas** [comment]
Fixed by #1133.
