### ISSUE TITLE
Tweak Version.selectNext

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1136]
`Version.selectNext` currently allows these updates:
```
org.apache.spark:spark-core:provided : 2.4.4 -> 3.0.0-preview
org.glassfish.jaxb:txw2 : 2.3.2 -> 2.3.3-b02
```
I think both should be forbidden because they go from a release version to a pre-release version. I think `b` is a shorthand for `beta` and `preview` should be added as pre-release identifier.

**Comment by manuelcueto** [comment]
Will take a look in the evening

**Comment by manuelcueto** [comment]
I couldn't find where to place `preview` in the order.
I only found somewhere that preview could be swapped with Alpha version so i'm giving it the same order. Let me know your thoughts on it

**Comment by fthomas** [comment]
Using the same order for `alpha` and `preview` is fine with me. AFAIK there are is no common understanding how `preview` is ordered compared to other pre-release identifiers. Version ordering is unfortunately a messy business.
