### ISSUE TITLE
Allow repo specific resolvers in CoursierAlg

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1141]
`CoursierAlg` currently looks for `pom.xml`s, `ivy.xml`s, and new versions in Coursier's default package repositories and in sbt-plugin-releases. It won't find any of those information for packages that are in repo specific repositories. As a prerequisite to replacing sbt-updates with `CoursierAlg` and to make it more useful in general, we need to change `CoursierAlg` so that it can take custom package repositories (and accompanying credentials) into account.

Here are references to other issues and PRs which make the case for this feature:
* https://github.com/fthomas/scala-steward/issues/1088#issuecomment-552585756
* https://github.com/fthomas/scala-steward/pull/1092
* https://github.com/fthomas/scala-steward/pull/1133#issuecomment-562848761

**Comment by manuelcueto** [comment]
By custom package repositories you mean private nexus and resolvers?

**Comment by fthomas** [comment]
Yes, exactly. Basically we need the ability to pass the information from `sbt resolvers` to `CoursierAlg`. sbt calls these [`Resolver`](https://www.scala-sbt.org/1.x/api/sbt/librarymanagement/Resolver.html) / [`Repository`](https://www.scala-sbt.org/1.x/api/sbt/librarymanagement/MavenRepository.html) and in Coursier these are just called [Repository](https://get-coursier.io/docs/api.html#repositories).

I think the first step would be a new task in `StewardPlugin` that outputs the resolvers as JSON. We then would need to store them in the `RepoCacheRepository` which we then could query in different places to pass the additional repositories to `CoursierAlg`.

**Comment by manuelcueto** [comment]
Sounds good. I'll take a look later. that would mean we still need to run Sbt though, right?

**Comment by fthomas** [comment]
Yes, but only to keep the cache of dependencies and resolvers fresh. We wouldn't need to run it to find dependency updates.
