### ISSUE TITLE
Release notes when scmUrl or homepage are set in parent pom

### ISSUE THREAD

**Issue by anilkumarmyla** [fthomas/scala-steward#1157]
When scm->url or homepage are set in parent pom rather than in the child pom, release notes/changelog links don't get generated

**Comment by anilkumarmyla** [comment]
Doing a quick search found https://github.com/lagom/lagom/pull/2549 where byte-buddy pom doesn't have scm->url or homepage https://github.com/raphw/byte-buddy/blob/master/byte-buddy/pom.xml but the parent pom does https://github.com/raphw/byte-buddy/blob/master/pom.xml#L17

**Comment by fthomas** [comment]
URLs are extracted from the pom in `CoursierAlg`. It seems that `coursier.Project` has a `parent` field which can be used to fetch the parent pom if the original pom has no SCM URL or homepage set.

**Comment by anilkumarmyla** [comment]
thanks @mzuehlke @fthomas I've spot checked https://github.com/scalameta/mdoc/pull/219 v/s https://github.com/scalameta/mdoc/pull/261 and it seems to be working
