### ISSUE TITLE
Make PR update behaviour configurable

### ISSUE THREAD

**Issue by kluen** [fthomas/scala-steward#1162]
As of #724, Scala Steward updates its pull requests only when they are in conflict with the base branch. This behaviour helps reducing the number of builds. However, it doesn't allow you to check for semantic conflicts which a successful git merge might have. This use case had been covered before the change.

This issue aims to make Scala Steward configurable so that the user can choose the new or the old (pre-#724) behaviour.

@fthomas also [mentioned some ideas](https://github.com/fthomas/scala-steward/pull/724#issuecomment-561362046) on how this might be implemented.

**Comment by fthomas** [comment]
Fixed by #1227.
