### ISSUE TITLE
Suppress major version upgrades while allowing minor version upgrades

### ISSUE THREAD

**Issue by dhoepelman** [fthomas/scala-steward#1163]
First of all, thanks for the great software

We're encountering scala-steward trying to upgrade dependencies with incompatities to other dependencies (e.g. [play-slick](https://github.com/playframework/play-slick) requires a specific play version so cannot be updated independently)

You can currently suppress these completely in `.scala-steward.conf`:

```
updates.ignore = [
   { groupId = "some", artifactId="some" },
]
```

It would be very nice if you could suppress automatic major-version upgrades, while allowing minor version upgrade. Which I don't think is possible with the current `version` syntax.

Could be something like this:
```
updates.ignore = [
   # Allow x to (x+1), default
   { groupId = "some", artifactId="some", upgrade = "major"},
   # Allow x.y to x.(y+1), but not x.y to (x+1).y
   { groupId = "some", artifactId="semver-compliant", upgrade = "minor"},
   # Allow x.y.z to x.y.(z+1), but not x.y to x.(y+1)
   { groupId = "some", artifactId="scala-number-style", upgrade = "patch"},
]
```

**Comment by fthomas** [comment]
You could use `updates.allow` and specify a prefix of the version:
```
updates.allow = [
  # Allow x.y to x.(y+1), but not x.y to (x+1).y
  { groupId = "some", artifactId="some", version="x." },
  # Allow x.y.z to x.y.(z+1), but not x.y to x.(y+1)
  { groupId = "some", artifactId="some", version="x.y." }
]
```
I think that should work.

**Comment by mwz** [comment]
Cool, it would be nice to mention about this in the docs.

**Comment by fthomas** [comment]
I agree that this needs to be documented.
