### ISSUE TITLE
Close older PRs if they're newer versions of the same dependency

### ISSUE THREAD

**Issue by kiranbayram** [fthomas/scala-steward#1231]
I was wondering if it would make sense if scala steward could close the older PRs if there're newer PRs for the same dependency. Number of latest PRs to keep could be a repo configuration.

At our company, when scala-steward PRs aren't maintained/cleared, it ends up having hundred of PRs which at the end useless and should be closed. I was wondering if scala steward could help with this by closing PRs it created

**Comment by mzuehlke** [comment]
is this the same as #119 ?

**Comment by kiranbayram** [comment]
Oh yes, you're right. Sorry, i've overlooked that one :)
