### ISSUE TITLE
Add the ability to use the default reviewers for Bitbucket server

### ISSUE THREAD

**Issue by andreami** [fthomas/scala-steward#1251]
Hi guys,

I added to my forked project the ability, for bitbucket server only, to use 
the default reviewers configured in the repository settings.

I just call the default-reviewers API of Bitbucket and add the list of the reviewer to the PR input.

Here the documentation:
https://docs.atlassian.com/bitbucket-server/rest/6.10.0/bitbucket-default-reviewers-rest.html

The feature can be enabled with the flag --use-default-reviewers that by default is set to false.

Here the link to the PR with my modification:
https://github.com/fthomas/scala-steward/pull/1250

**Comment by mzuehlke** [comment]
I think this can be closed, because #1250 got merged.

**Comment by andreami** [comment]
I agree, sorry
