### ISSUE TITLE
Fetch tags in GitAlg.syncFork

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1284]
I think we also need to fetch tags in `GitAlg.syncFork` because some repos require tags to be present in order for the build to load successfully. See for example https://github.com/almond-sh/almond/pull/483.

**Comment by kiranbayram** [comment]
Hello there, i can give this a go. Do we want this behind a configuration ? And to be clear, what we need to do is both:
 - git fetch
 - git fetch --tags
is that right ?

**Comment by kiranbayram** [comment]
Or do we need to use `git fetch --tags` instead of `git fetch` ? And which git version do we use?

**Comment by fthomas** [comment]
No, this shouldn't be behind a configuration. It should just be the default behaviour. And we don't know which Git version is used, we're just using the git command that is provided in the environment Scala Steward is running in.

With regard to the right git command(s): I assume that adding `--tags` would be enough.
