### ISSUE TITLE
Include changelog AND release notes in PR body

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1285]
When Scala Steward creates a PR it tries to find a URL for a changelog or the release notes and if found includes this in the PR body. Some projects still have an old changelog around but switched to GitHub release notes ([doobie](https://github.com/tpolecat/doobie/blob/7dd53820309045dc84d103a31cceeb0ddf71fc94/CHANGELOG.md) is one example). For these projects Scala Steward includes the URL to the outdated changelog instead to the more helpful and up-to-date release notes in the PR. I therefore think we should always include both URLs in the PR.

**Comment by kiranbayram** [comment]
I started working on this. Is the way displayed below okay?
For 1 url -> [Release Notes/Changelog](url1)
For 2 urls -> [Release Notes/Changelog](url1) - [Release Notes/Changelog 2](url2)

**Comment by fthomas** [comment]
It would be great if the link to the GitHub release notes would use "GitHub release notes" (or something similar) as text. I think Scala Steward should keep track of what it found when it looks for interesting URLs. Maybe instead of bare `URI`s we should use a `sealed trait` with subclasses like `VersionDiff`, `CustomChangelog`, `CustomReleaseNotes`, `GitHubReleaseNotes` that each wrap a `URI`.

**Comment by kiranbayram** [comment]
Do we want to limit the max number of release related urls to 2 ?

**Comment by kiranbayram** [comment]
which are displayed in PR body

**Comment by mzuehlke** [comment]
Why restrict the information. As a developer, who has to decide on the implications of merging a PR, I want as many information as possible.
Currently, we are showing (if possible) a GitHub diff either a changelog or the GitHub release.
If we can in the future show information, I would like that.
The 4 types of `URI` @fthomas mentions above could, in my opinion, all be shown in the same PR.

**Comment by fthomas** [comment]
I agree with @mzuehlke, let's include all URLs Scala Steward finds. We can always add a limit later if we find out that there are cases where Scala Steward includes too much.

**Comment by kiranbayram** [comment]
Alright, i agree with that too. I'll try it that way 👍

**Comment by kiranbayram** [comment]
This should be closed now
