### ISSUE TITLE
Add support for giter8

### ISSUE THREAD

**Issue by d10xa** [fthomas/scala-steward#1286]
Is it possible to add giter8 templates? Templates contains all sources at `src/main/g8`. 
For example, build.sbt can be found here `src/main/g8/build.sbt`

example https://github.com/foundweekends/giter8.g8
docs http://www.foundweekends.org/giter8/template.html#template+layout

**Comment by fthomas** [comment]
Yes, Scala Steward can update versions in giter8 templates if the dependencies of the template are also added as dependencies of the template build. See https://github.com/ChristopherDavenport/library.g8/pull/100/files for example. I think this works good enough and warrants no special support for giter8 in Scala Steward.

**Comment by d10xa** [comment]
Thank you. This is works good enough

**Comment by awwsmm** [comment]
Hey @fthomas could you explain _how_ this works? How does Scala Steward "know" that the two `build.sbt`s are related?

**Comment by fthomas** [comment]
It does not know that the `build.sbt`s are related. Once it extracts a dependency from the build, it forgets where that was coming from (i.e. the build/file where that dependency is defined). When it then updates a dependency it updates all plausible looking dependency definitions and if the definitions in `build.sbt` and `src/main/g8/build.sbt` are equal, both are updated.
