### ISSUE TITLE
Extract credentials from sbt and pass them to Coursier

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1291]
Some package repositories require credentials for checking which versions of an artifact are available but we currently ignore credentials when extracting information from sbt. To support finding updates in private package repositories that require credentials for read access, we need to include credentials in `StewardPlugin`'s `stewardDependencies` task, add them to [`Scope`](https://github.com/fthomas/scala-steward/blob/83b85f1edad64e8ad7a024e556f9f89cb0ffbb23/modules/core/src/main/scala/org/scalasteward/core/data/Scope.scala), and pass them to Coursier in `CoursierAlg`.

sbt has two types of credentials, [`DirectCredentials`](https://www.scala-sbt.org/1.x/api/sbt/librarymanagement/ivy/DirectCredentials.html) and [`FileCredentials`](https://www.scala-sbt.org/1.x/api/sbt/librarymanagement/ivy/FileCredentials.html) and I think we should also support both.

**Comment by ahjohannessen** [comment]
As a workaround I managed to get scala-steward & coursier to work by doing this:

```shell
$ cat scala-steward/credentials.properties
stash.username=****
stash.password=****
stash.host=example.com
stash.auto=true
```
and pass `-J-Dcoursier.credentials=/opt/scala-steward/credentials.properties` to scala-steward.
