### ISSUE TITLE
Missing version diff url in Pr body

### ISSUE THREAD

**Issue by kiranbayram** [fthomas/scala-steward#1311]
I was checking some PRs to see the new release related urls and noticed there're no urls for [this one](https://github.com/lucidd/rpm4s/pull/102), even though such [diff url](https://github.com/portable-scala/sbt-crossproject/compare/v0.6.1...v1.0.0) exists.

**Comment by fthomas** [comment]
I guess the reason for this is that the `ivy.xml` or `pom.xml` of that plugin does not contain the URL to its GitHub repo.

**Comment by fthomas** [comment]
Yep, https://dl.bintray.com/sbt/sbt-plugin-releases/org.portable-scala/sbt-scalajs-crossproject/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml does not contain the `homepage` attribute which would have been read in `CoursierAlg` and which is the base URL for finding version diffs, release notes, and changelogs.

**Comment by kiranbayram** [comment]
Ah okay, thanks for the explanation 👍😊
