### ISSUE TITLE
Look for corresponding changes in things like '.md' files

### ISSUE THREAD

**Issue by erikerlandson** [fthomas/scala-steward#1376]
I don't know how common this use case is, but I have some dependencies that also appear in my markdown docs, for example:

```
how to install:

```scala
resolvers += "manyangled" at "https://dl.bintray.com/manyangled/maven/"

libraryDependencies ++= Seq(
  // basic coulomb dependencies
  "com.manyangled" %% "coulomb" % "0.3.6",
  "org.typelevel" %% "spire" % "0.17.0-M1",
  "eu.timepit" %% "singleton-ops" % "0.4.0",
  // pureconfig integration:
  "com.manyangled" %% "coulomb-pureconfig" % "0.3.5",
  "com.github.pureconfig" %% "pureconfig" % "0.12.0"
)
```

Using the example above, if scala steward updated the pureconfig dep in my sbt build, in theory it also might update it in my markdown.

**Comment by mzuehlke** [comment]
This could be the same as #1006

**Comment by erikerlandson** [comment]
@mzuehlke It definitely seems related.
Maybe something inspired by .gitignore - a `.scala-steward-files` file that lists individual files or glob patterns where scala-steward will update version patterns it finds?  So, I would put `*.md` in mine, but maybe someone else would choose not to.

**Comment by fthomas** [comment]
I'm also fine with adding `".md"` here: https://github.com/fthomas/scala-steward/blob/e1e4179e32a7134f442f42e492ec401c9966d990/modules/core/src/main/scala/org/scalasteward/core/io/package.scala#L38.

**Comment by erikerlandson** [comment]
That would definitely work from my PoV

**Comment by erikerlandson** [comment]
@fthomas Shall we reopen this and maybe consider a `.scala-steward` file that just lists files and glob patterns?  Or is there some variable in sbt that could be set?

**Comment by mzuehlke** [comment]
@alejandrohdezma made good suggestion (https://github.com/fthomas/scala-steward/issues/1394#issuecomment-611503767) to use Mdoc.

Another option would be to limit changes to markdown files in a way that they are only possible, if the same change had an effect on a `sbt` file.
 this would at least eliminate all the PRs that only changed documentation.

**Comment by erikerlandson** [comment]
mdoc would probably work.  Intuitively, it seems "right" to me that a robot whose job it is to update version strings should have some kind of api for configuring _which_ files it updates on any given repo. However, that is the kind of thing where people's opinions differ widely, so if the solution is "you should use mdoc" I could adapt to that.

**Comment by fthomas** [comment]
I think agree with both positions. Sometimes projects define their version numbers in weird places which Scala Steward does not modify by default. It could be useful then if users are able to tell Scala Steward which files it is should to modify.
And if projects use only a single source of truth for their version numbers it will be easier for Scala Steward (or any other robot, or even humans) to update the correct version string.

**Comment by erikerlandson** [comment]
I may try mdoc, since it would also save me having to remember where to update my _own_ release strings. But I still wouldn't say no to some kind of configuration knob.
