### ISSUE TITLE
Configurable path for `.scala-steward.conf`

### ISSUE THREAD

**Issue by anilkumarmyla** [fthomas/scala-steward#1411]
Currently scala steward config is looked up at the top of repo `<repo>/.scala-steward.conf` and there is no way to specify an alternate location for it. 

Our use-case (as bizarre as it seems) is we want to have two different scala steward configs and run two instances of scala steward with the configs at different times/frequency. 

Some dependencies update too frequently and we want to be able to stagger the updates by having an ignore rule in one config and omitting it in the other. This way we can run the first instance as much as we want and occasionally run the second instance (with different config) whenever we seem to care about an update to this dependency. What do you think?

**Comment by fthomas** [comment]
If you could set the PR frequency for individual dependencies, would that solve the underlying issue?

**Comment by anilkumarmyla** [comment]
Yes! but in its current shape I cannot fathom how we can define pull-request frequency for a specific dependency

**Comment by anilkumarmyla** [comment]
PR #1483 provides a way to achieve our use-case
