### ISSUE TITLE
scalafixDependencies not updated for scala 2.13

### ISSUE THREAD

**Issue by anilkumarmyla** [fthomas/scala-steward#1413]
We have the following in build.sbt
```
scalaVersion := "2.13.2"
...
scalafixDependencies in ThisBuild ++= Seq(
  "com.nequissimus" %% "sort-imports" % "0.3.2"
)
```

Strangely scala-steward does not find an update for sort-imports, but finds it when we downgrade scalaVersion to 2.12.11. 

Interestingly that module is only published for scala 2.12 but somehow magically works on scala 2.13 as well 🤔

**Comment by anilkumarmyla** [comment]
This may have strong connection to https://github.com/scalacenter/scalafix/issues/998

**Comment by fthomas** [comment]
Maybe an easy workaround could be to not use `%%` and define the Scalafix dependency as `"com.nequissimus_2.12" % "sort-imports" % "0.3.2"`?

**Comment by anilkumarmyla** [comment]
nope, fails to download
```
[error] coursierapi.error.SimpleResolutionError$1: Error downloading com.nequissimus:sort-imports:0.3.2
[error]   not found: /Users/anilkumarmyla/.ivy2/local/com.nequissimus/sort-imports/0.3.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/nequissimus/sort-imports/0.3.2/sort-imports-0.3.2.pom
[error]   not found: https://oss.sonatype.org/content/repositories/public/com/nequissimus/sort-imports/0.3.2/sort-imports-0.3.2.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/nequissimus/sort-imports/0.3.2/sort-imports-0.3.2.pom
```

**Comment by fthomas** [comment]
:rofl: Of course the Scala binary version goes onto the artifactId and not the groupId. Sorry for that silly mistake.

**Comment by anilkumarmyla** [comment]
@fthomas Thanks for the pointer, scala-steward works with the _2.12 hack when scalaVersion is 2.13.x ! Feel free to close

**Comment by anilkumarmyla** [comment]
@fthomas seems like after the workaround, we got bad PRs again, should we also include sort_imports_2.12 as done in https://github.com/fthomas/scala-steward/pull/1354 
`Update sort-imports_2.12 to 36845576`
`Updates com.nequissimus:sort-imports_2.12 from 0.5.0 to 36845576.`

**Comment by fthomas** [comment]
Yes, I think it is reasonable to add `sort-imports_2.12` there.
