### ISSUE TITLE
Also update scala version

### ISSUE THREAD

**Issue by erikvanoosten** [fthomas/scala-steward#145]
It looks like scala-steward doesn't try to update the scala version.

For example in the build.sbt of metrics-scala we have: `scalaVersion := "2.12.6"` and `crossScalaVersions := Seq("2.11.12", "2.12.6")`. Version 2.12.7 is already out.

**Comment by fthomas** [comment]
I found that updating the Scala version is trickier and more error-prone than updating libraries or plugins. E.g in most of my projects the Scala version is only defined in the `.travis.yml` file. The naive approach also generated some bad PRs like this one: https://github.com/fthomas/singleton-ops/pull/76/files. If we find a reliable way to update the Scala version, I'm all for letting scala-steward do it.

**Comment by erikvanoosten** [comment]
Neat. I have never seen that. I still prefer to have scala versions in my build.sbt.

What about a simple heuristic that only matches: `scalaVersion := "([^"]+)"` and `crossScalaVersions := Seq\(("([^"]+)")+\)`? Presumably this will catch most usages.

For the second pattern only minor versions should be suggested. If a new major version is available, the suggestion could be to add it to the sequence.

**Comment by thesamet** [comment]
With all the 2.13 milestones and RCs coming out - it would be really nice to have scala-steward able to push us all to the latest versions. Since those milestones and RCs are not binary compatible, scala-steward would have to check that all dependencies have been published for that specific version before making a PR.

**Comment by nafg** [comment]
I don't get the benefit of having the scala version in .travis.yml -- then needing to pass `++$TRAVIS_SCALA_VERSION` to sbt.

It seems much easier to use `crossScalaVersions` in `build.sbt` and then just put a `+` before the sbt command. Besides, the build is then much more portable and reproducible.

**Comment by anilkumarmyla** [comment]
Is this something that can be done under a special command-line flag that can be turned on by people interested in this? Honestly I would settle for a bad PR (that breaks the build and needs intervention) than no PR at all for scala upgrades 🙂

**Comment by fthomas** [comment]
@anilkumarmyla The code that prevents updating Scala is [here](https://github.com/fthomas/scala-steward/blob/381670a4d38978d1e8e725d45cb4d5e233e15e19/modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala#L78-L81). I'm open to adding a new flag to `.scala-steward.conf` that overrules these lines.

**Comment by anilkumarmyla** [comment]
@fthomas Thanks for the pointer, here is my attempt #1381

**Comment by SethTisue** [comment]
see #589 for further discussion on this
