### ISSUE TITLE
Launch Scala Steward with Coursier

### ISSUE THREAD

**Issue by alejandrohdezma** [fthomas/scala-steward#1453]
It would be ideal to be able to launch Scala Steward using Coursier like:

```bash
cs launch scala-steward
```

To be able to do these, two things would be needed:

- [x] Publish a new version of Scala Steward for Scala 2.13
- [ ] Publish Scala Steward as a Coursier app following [this guide](https://get-coursier.io/docs/cli-install.html#creating-your-own-applications)

I can do the second one once a new version gets published

**Comment by fthomas** [comment]
I've just published Scala Steward 0.6.0 is for Scala 2.13: https://repo1.maven.org/maven2/org/scala-steward/scala-steward-core_2.13/0.6.0/

**Comment by alejandrohdezma** [comment]
That's great! I can start working on the coursier app ASAP :) Thanks @fthomas

**Comment by alejandrohdezma** [comment]
Done!

Scala Steward can now be launch with:

```bash
cs launch --contrib scala-steward
```

(or installed):

```bash
cs install --contrib scala-steward
```

**Comment by fthomas** [comment]
Awesome, many thanks @alejandrohdezma!
