### ISSUE TITLE
Track releases for resolver jitpack.io

### ISSUE THREAD

**Issue by Synesso** [fthomas/scala-steward#1472]
Where a build includes the resolver `"https://jitpack.io"`, can we track those dependency upgrades?

For example, [this project](https://github.com/Synesso/scala-stellar-horizon-exemplar/blob/master/build.sbt)

**Comment by exoego** [comment]
Yes, I believe Scala steward can track dependency in custom resolver, as long as the resolver(s) are defined in build, and proper credential(s) are give if needed.
See https://github.com/fthomas/scala-steward/issues/319#issuecomment-575882277

I am using private-hosted Scala steward. It works fine with private resolver.

**Comment by Synesso** [comment]
Cool. Maybe i didn’t give it enough time.

Or maybe it’s because the version changed from random sha to v0.0.1 and
that’s not recognised as an upgrade,

Thanks for the reply
