### ISSUE TITLE
Mill integration failed to resolve build dependency

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#1499]
This happened while Scala Steward tried to extract dependencies from https://github.com/ToToTec/CmdOption:

```
'mill -i -p /home/frank/scala-steward/workspace/repos/ToToTec/CmdOption/scala-steward.sc show org.scalasteward.mill.plugin.StewardPlugin/extractDeps' exited with code 1
Compiling /home/frank/scala-steward/workspace/repos/ToToTec/CmdOption/scala-steward.sc
Downloading https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
Downloaded https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
Downloading https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom.sha1
Downloaded https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
Downloaded https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
Downloading https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom.sha1
Downloaded https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom.sha1
Failed to resolve ivy dependencies:Error downloading de.tototec:de.tobiasroeser.mill.osgi_2.13:0.2.0
  not found: /home/frank/.ivy2/local/de.tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
```
Mill couldn't resolve the de.tobiasroeser.mill.osgi plugin which is imported in the build of ToToTec/CmdOption.

@hamnis @lefou Any idea how to fix this?

**Comment by hamnis** [comment]
@fthomas as I mentioned on gitter. this repo seems to be using mill 0.6 and the plugin is using mill 0.7 ... I never found a way to make both work satisfactory.

Mill 0.7 is Scala 2.13 and that is probably the reason.
@lefou might be able to shed some more light on this.

**Comment by hamnis** [comment]
@fthomas how is the mill script installed ? 
It needs to respect the `.mill-version` file, or env variable `MILL_VERSION`.

I finally found a way to integrate 0.6 and PR is coming shortly.

**Comment by lefou** [comment]
Yeah, this project is still on mill 0.6, but I will upgrade it soon. Although I don't think we need to support mill 0.6 and older, it is still a good example and reminder that we should treat version differences seriously. The exact mill version to use is in most cases specified in a `.mill-version` file in the root of the project. This is supported by the `mill` script provided by mill itself as well as the [`millw`](https://github.com/lefou/millw) launcher (which has also a version working under Windows), so invoking some random script in the repository should be avoided IMHO (These are in most cases only convenience for CI or temporary developers).

**Comment by lefou** [comment]
Thinking about it, as scala-steward is all about version upgrades, we could even try to upgrade the used mill version as well as the used mill plugin versions.

**Comment by fthomas** [comment]
> @fthomas how is the mill script installed ?

I used Coursier to install it: `cs install mill-interactive` and then symlinked `mill` to `mill-i`.

**Comment by fthomas** [comment]
> Thinking about it, as scala-steward is all about version upgrades, we could even try to upgrade the used mill version as well as the used mill plugin versions.

Sure. We're doing the same for sbt and sbt plugins, so I've no ojbection to do it for mill, too. We should open a new issue for this feature request.

**Comment by fthomas** [comment]
It seems that #1501 wasn't sufficient to fix this problem:
```
2020-07-04 13:21:24,081 ERROR Check cache of ToToTec/CmdOption failed
java.io.IOException: 'mill -i -p /home/frank/scala-steward/workspace/repos/ToToTec/CmdOption/scala-steward.sc show org.scalasteward.mill.plugin.StewardPlugin/extractDeps' exited with code 1
Compiling /home/frank/scala-steward/workspace/repos/ToToTec/CmdOption/scala-steward.sc
Downloading https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
Downloaded https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
Downloading https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom.sha1
Downloaded https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
Downloaded https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
Downloading https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom.sha1
Downloaded https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom.sha1
Failed to resolve ivy dependencies:Error downloading de.tototec:de.tobiasroeser.mill.osgi_2.13:0.2.0
  not found: /home/frank/.ivy2/local/de.tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/de/tototec/de.tobiasroeser.mill.osgi_2.13/0.2.0/de.tobiasroeser.mill.osgi_2.13-0.2.0.pom
```
Could it be the case that the `mill` binary in the `PATH` also need to be a 0.6 version? Scala Steward is currently using Mill 0.7.3:
```
$ mill --version
Mill Build Tool version 0.7.3
```

**Comment by lefou** [comment]
Yeah, that's that the point of using an older version. It needs to use the older runtime. Specifically, mill changed it's Scala version beween 0.6.x and 0.7.x, so a build for 0.6.x will most probably always fail if it is using additional external plugins, which is the case here.

**Comment by lefou** [comment]
Oh sorry, I somehow missread your message. I think mill does not invoke any `mill` binary it found on the `PATH`. So, it should make no difference what's their binary version.

**Comment by lefou** [comment]
To summary: If you try to run a `build.sc` with is intended for mill `0.6.x` than that means it uses mill's 0.6 API and Scala 2.12 and  also requires to load mill plugins for this environment. if you now do that with a mill 0.7.x runtime it will most probably fail. In this case, the used mill plugin `mill-osgi` in version `0.2.0` was never released for mill 0.7.x, hence there is no Scala 2.13 version of it.

**Comment by fthomas** [comment]
> I think mill does not invoke any `mill` binary it found on the `PATH`

But Scala Steward invokes the `mill` binary on the `PATH` to load the build and determine the dependencies. 

> if you now do that with a mill 0.7.x runtime it will most probably fail.

Ok, so is the `mill` binary installed by Coursier (which is a 0.7.x version) a mill 0.7.x runtime? I guess Scala Steward then needs to invoke different commands depending on the used mill version?

**Comment by lefou** [comment]
I'm sorry for not being familiar how the coursier installment of mill works. The idea how mill builds should works is: respect whatever version is given via `.mill-version` file or `MILL_VERSION` environment variable, and use a mill runtime with exactly that version. That's also how the `mill` script bundled with mill behaves. I think the metals developers use a version of `lefou/millw` to ensure exactly the same behavior.

**Comment by fthomas** [comment]
I think Coursier bundles the latest Mill JAR to an executable ([ref](https://github.com/coursier/apps/blob/a757bd891b3d1ff33e6e96db6f31fed6fdba13de/apps/resources/mill-interactive.json)) and that does not work for Scala Steward since it only supports one Mill version. I'm now trying out `millw` as `mill` executable in the `PATH`. :crossed_fingers:

**Comment by fthomas** [comment]
It worked with `millw`: https://github.com/ToToTec/CmdOption/pull/25 :tada: 

Thanks @lefou for guiding me through this and thanks again @hamnis for #1501.

**Comment by lefou** [comment]
Thank you for your great engagement!
