### ISSUE TITLE
`javac` missing in the docker image

### ISSUE THREAD

**Issue by joan38** [fthomas/scala-steward#1518]
```
[error] ## Exception when compiling 72 sources to /opt/scala-steward/workspace/repos/SDE/playback-summarizer/target/scala-2.12/classes
[error] java.io.IOException: Cannot run program "javac" (in directory "/opt/scala-steward/workspace/repos/SDE/playback-summarizer"): error=2, No such file or directory
```
For repos containing some Java files.

To me this is because we should be using `openjdk:8-jdk-alpine` instead of `openjdk:8-jre-alpine` in https://github.com/fthomas/scala-steward/blob/master/build.sbt#L196

If people agree on this, I can make the PR.
Let me know.

**Comment by fthomas** [comment]
I've no objection to changing the base image.

A related thought I had recently was if it would be easier to use [`cs setup`](https://www.scala-lang.org/2020/06/29/one-click-install.html) to install a JDK, sbt, maven, mill than what [we're currently doing](https://github.com/fthomas/scala-steward/blob/fcf491d2efe60a0fb4461da4ee461be9c6083d83/build.sbt#L198-L207).

**Comment by joan38** [comment]
`curl: not found` curl is not even on openjdk alpine

**Comment by fthomas** [comment]
I guess we could install `curl` with `apk` [here](https://github.com/fthomas/scala-steward/blob/7732e4c47125fe9ff4e2157d43cf6709532dbe94/build.sbt#L205).

**Comment by joan38** [comment]
I've not been able to make the cs exec work on alpine. Ubuntu is ok tho.

**Comment by fthomas** [comment]
We moved from a Debian based image to Alpine in #1370 because of the image size. It this point I'd accept a PR changing the base image to `openjdk:8-jdk-alpine` and defer using Coursier to another time.
