### ISSUE TITLE
Support markup to ignore single or multiple lines

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#192]
see https://github.com/erikvanoosten/metrics-scala/pull/118

**Comment by erikvanoosten** [comment]
The annotation `scala-steward:ignore` for a single line, and

    scala-steward:off
    ...
    scala-steward:on

for multi-line would be nice. But something like:

    scala-steward:only 2.4.x
    scala-steward:only 2.x

(with any appropriate expression syntax) would be even more useful!

**Comment by exoego** [comment]
@erikvanoosten
FYI: `scala-steward:(on:off)` markup was added in #671.
