### ISSUE TITLE
Interest in making scala-steward work without forking

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [fthomas/scala-steward#197]
Hi @fthomas 

Thanks for this great bot. I love it. 

I have some interest in making `scala-steward` work for repositories that don't have the luxury of allowing `forks` and limits users to work with branches out of one main repository.

I tried to tweak scala-steward to my use-case and got it to work. (Needs some clean up)
https://github.com/ArulselvanMadhavan/scala-steward/commit/18a3b11d8c5555363a111487bf13d66e0e21e037

If you are interested in adding this as a feature behind a config flag(or some other better option), let me know. I would like to contribute towards that effort.

**Comment by fthomas** [comment]
Implemented in #208.
