### ISSUE TITLE
Interest in adding a list of companies using scala-steward to the readme

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [fthomas/scala-steward#244]
Since #197  is merged, `scala-steward` can work on any repo regardless of the git workflow an organization chooses to use. So, companies now have the option of using it on their internal private repos. This issue is to see if there is any interest in adding a list of companies that are using `scala-steward` somewhere in the repo to be well informed of the community that is benefiting from `scala-steward`.

Something similar to https://github.com/circe/circe#community

@fthomas  Thoughts?

**Comment by fthomas** [comment]
Sounds good to me.

**Comment by plokhotnyuk** [comment]
Beware,  that the https://github.com/circe/circe#community list is a two edged sword. In case of any discovered vulnerability it will switch to the list of affected businesses.

**Comment by fthomas** [comment]
Added in #245.
