### ISSUE TITLE
Do not change version numbers in comments

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#249]
see https://github.com/coursier/sbt-coursier/pull/19

**Comment by kiranbayram** [comment]
Hi @fthomas , i'm looking into this bug and i tried to find a way to fix it in regex only but didn't succeed. Do you think it is even possible to fix it in regex only ?

**Comment by fthomas** [comment]
Maybe, but there is a simpler way to prevent changing line comments. [`group1`](https://github.com/fthomas/scala-steward/blob/cc5dccf7f62ac2f001fc500db97657ed1ab8cf91/modules/core/src/main/scala/org/scalasteward/core/model/Update.scala#L57) contains all characters before a search term that matches the artifactId, so if `group1` starts a line comment with `//` returning `None` there should fix this bug.

**Comment by fthomas** [comment]
Fixed by #426.
