### ISSUE TITLE
Update to version number val used by multiple libraries breaks build

### ISSUE THREAD

**Issue by DougC** [fthomas/scala-steward#277]
This PR https://github.com/WellFactored/clovis/pull/15 updates the version number of `enumeratum-circe` by changing the value of `enumeratumVersion` from 1.5.13 to 1.5.19. However, that val is also used to define the version of the core `enumeratum` library, which does not have a 1.5.19 version, so the subsequent build breaks.

**Comment by fthomas** [comment]
It seems to me that `enumeratum` and `enumeratum-circe` have different release cycles and version numbers. Would it make sense to use two vals then for those dependencies?

**Comment by DougC** [comment]
Yeah, I can definitely change the build.sbt to avoid this. In fact, I've already done so by not explicitly depending on `enumeratum` and letting it be pulled in as a transitive dependency of `enumeratum-circe`. But the main point I was raising is that sometimes `scala-steward` makes changes that break the build in this way. I don't know if you think it's worth trying to detect a situation like this, where the variable is used in two places, and resolving it somehow.

**Comment by fthomas** [comment]
scala-steward is currently a beefed-up text-based "search and replace". To reliably detect such situations it would need to have a semantic understanding of the things it is trying to change (probably via scalameta) but we're not there yet. Until then I think trying to detect such situations would be like a game of whack-a-mole.

**Comment by DougC** [comment]
Fair enough. I really opened this issue to discuss the implications of this. In fact, what I've realised is that scala-steward has been helpful in pointing me at the anomaly in my build.sbt, so that's been valuable. I'll close this issue now.

Thanks very much for making such a useful tool!
