### ISSUE TITLE
support mill

### ISSUE THREAD

**Issue by Krever** [fthomas/scala-steward#314]
It would be nice for scala-steward to be able to work with [mill](http://www.lihaoyi.com/mill/) and maybe other build tools as well. As I understand this requires three components: 
1. read dependencies from build
2. rewrite dependencies in build file
3. find newer dependencies

I believe the 3) could be shared between build tools, but I dont know hard would that be. 
It would be nice to learn how hard 1) and 2) could be.

I assume 1) is as simple as executing proper mill command and parsing the results.
2) sounds like could be done with scalafix, but I dont know it well enough to say something for sure.

**Comment by nafg** [comment]
IIRC mill already has a builtin to check for updates? But it won't rewrite the code will it?

**Comment by fthomas** [comment]
You can strike point two from your list. scala-steward is build-tool-agnostic when it comes to updating versions in source files. It "just" uses text search and replace to update versions in source files. 3) will be the hard part for which scala-steward uses the sbt-updates plugin.

**Comment by nafg** [comment]
3 is built into it. `mill mill.scalalib.Dependency/updates`

**Comment by fthomas** [comment]
This is great! Then only scala-steward needs be changed to call the right mill commands. I'm looking forward to the PR. :-)

**Comment by Baccata** [comment]
I had a very quick dive into the code. Is the following analysis correct ? 

* The algebra that needs to be provided with an alternate implementation is `SbtAlg` ? 

* SbtAlg currently exposes a reference to `ArtificialProject` in its interface, the concept of which seems to be fairly coupled to Sbt itself. Maybe `ArtificialProject` should be a path dependant type both produced and consumed by `SbtAlg`, so that a similar type can be established for other build tools (if necessary)  

* steward currently implements a mechanism that expects the build tool to dump a json representation of the dependencies involved in the repo. Is there an example (or schema) of the json ?

**Comment by fthomas** [comment]
> * The algebra that needs to be provided with an alternate implementation is
> `SbtAlg` ?

Yes, but you only need to provide alternative implementations for
`getDependencies` and `getUpdatesForRepo` (this is the most important one).

> * SbtAlg currently exposes a reference to `ArtificialProject` in its
> interface, the concept of which seems to be fairly coupled to Sbt itself.

That's okay. This class is used to find updates of all artifacts scala-steward
knows about. We can continue to use that even if we add support for other
build tools.

> * steward currently implements a mechanism that expects the build tool to
> dump a json representation of the dependencies involved in the repo. Is
> there an example (or schema) of the json ?

Here are some examples: https://github.com/fthomas/scala-steward/blob/master/
modules/core/src/test/scala/org/scalasteward/core/dependency/parserTest.scala

**Comment by joan38** [comment]
+1 on this

**Comment by fthomas** [comment]
FYI: Scala Steward does not need the build system any more for finding dependency updates since #1209. This should make it easier to add support for other build systems. Anyone looking into adding support for Mill should also look into #1193 which adds support for Maven.

**Comment by fthomas** [comment]
#1429 made adding support for other build system a lot easier. The only thing required now is an implementation of `BuildSystemAlg` (to get the dependencies from the build) and plugging it into `BuildSystemDispatcher`.
