### ISSUE TITLE
Unresolved dependency from plugins.sbt with external resolver

### ISSUE THREAD

**Issue by RoccoMathijn** [fthomas/scala-steward#319]
We have a custom sbt plugin that is hosted at the companies artifactory. I think the resolver that is defined in plugins.sbt is not being used when checking updates for this plugin.

Our plugins.sbt looks like this:

```
externalResolvers := Seq("Company Repo" at "https://repo.company.io/artifactory/")

addSbtPlugin("io.company" % "company-plugin" % "0.1.15")
```

The error we’re getting when running Scala Steward
```java.io.IOException: [info] Loading settings for project global-plugins from sbt-updates.sbt ...
[info] Loading global plugins from /root/.sbt/1.0/plugins
[info] Loading settings for project updates-build from plugins.sbt ...
[info] Loading project definition from /home/jenkins/workspace/updates/project
[info] Updating ProjectRef(uri("file:/home/jenkins/workspace/updates/project/"), "updates-build")...
[warn]     module not found: io.company#company-plugin;0.1.15
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/io.company/company-plugin/scala_2.12/sbt_1.0/0.1.15/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.company/company-plugin/scala_2.12/sbt_1.0/0.1.15/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /root/.ivy2/local/io.company/company-plugin/scala_2.12/sbt_1.0/0.1.15/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/company/company-plugin_2.12_1.0/0.1.15/company-plugin-0.1.15.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /root/.sbt/preloaded/io.company/company-plugin/0.1.15/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////root/.sbt/preloaded/io/company/company-plugin_2.12_1.0/0.1.15/company-plugin-0.1.15.pom
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     ::          UNRESOLVED DEPENDENCIES         ::
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     :: io.company#company-plugin;0.1.15: not found
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
```

And thanks for the awesome project. We're running it successful in production for a few weeks on 10+ repos!

**Comment by fthomas** [comment]
I'll explain later why this happens, but there is a workaround (https://github.com/fthomas/scala-steward/pull/253#issuecomment-462130792) which will prevent these errors.

**Comment by RoccoMathijn** [comment]
Thanks, that works like a charm!

**Comment by fthomas** [comment]
Here is the reason why this happens: Scala Steward tries to be smart about the repositories it is working on by ignoring those repos that are already up-to-date or where it would do nothing. It wouldn't scale if Scala Steward regularly works on hundreds or thousands of repos of which only a few would receive pull requests. So it prunes repos by building a cache of all dependencies of all repos and then checking for updates of those dependencies before it decides which repos it needs to work on. And while we build this cache of dependencies we ignore the resolvers where they can be resolved and assume that they can be resolved through the public default resolvers in sbt. This assumption is not true for company-internal dependencies and thus Scala Steward fails with an `UNRESOLVED DEPENDENCIES` error.

**Comment by fthomas** [comment]
With #1226 and #1237 Scala Steward now uses only the resolvers defined in the build to find updates. So it will also find updates of private library and plugin dependencies when pruning repos.
