### ISSUE TITLE
Firejail doesn't work in Docker

### ISSUE THREAD

**Issue by mwz** [fthomas/scala-steward#347]
Hi @fthomas, I've discovered that firejail doesn't work in Docker:
```bash
$ firejail echo hello
Warning: an existing sandbox was detected. echo will run without any additional sandboxing features
```

Running it with the `--force` flag, which is supposed to disable the PID namespace checking, results in the following error:
```bash
$ firejail --force echo hello
Error clone: main.c:2519 main: Operation not permitted
```

Additionally, the `--force` flag was removed in firejail 0.9.54 and apparently it is not possible to run firejail in Docker anymore (I asked about this recently https://github.com/netblue30/firejail/issues/2579).

I think we should remove firejail from scala-steward docker image and force it to run without the sandbox when the command isn't found or make it explicit in the docs that the sandboxing features don't work when running scala-steward in Docker.

**Comment by fthomas** [comment]
Oh no...

Removing firejail from the Docker image and adding a note to the docs to run it with `--disable-sandbox` in Docker seems fine to me.

Btw, thanks for investigating this!
