### ISSUE TITLE
Firejail opens firefox but there is no internet

### ISSUE THREAD

**Issue by caloona** [fthomas/scala-steward#362]
I just set up my laptop with a fresh iintall of ubuntu  18.04
When installing firejail thru the app centre all went fine 
Later i found out there was a update (firejail_0.9.56-LTS_1_amd64.deb) which i installed and than things went wrong.
I can open firefox but there is no internet  i even can't open my FF extensions
I'm no good in technical stuff so please step by step please.
I love FJ and FT and i definatly want to keep using, but righ now im lost.
Please help

**Comment by fthomas** [comment]
I can't help you with firejail questions. You'll have more luck asking questions about firejail here https://firejail.wordpress.com/support/ or here https://github.com/netblue30/firejail/issues
