### ISSUE TITLE
Document how to structure dependencies to optimally work with scala-steward

### ISSUE THREAD

**Issue by yannick-cw** [fthomas/scala-steward#377]
I am wondering if there are things which prevent scala-steward from working properly and updating dependencies. Is there some documentation how to structure or NOT to structure the dependencies?

**Comment by fthomas** [comment]
Currently there is no documentation about that. But you're right, there are ways which makes it easy for scala-steward to bump version numbers and ways which make it outright impossible to bump them. For example, the line where the version is defined needs to contain parts of the artifactId in front of the version. So if you'd define the version like this
```scala
val catsVersion =
  "1.6.0"
```
scala-steward would not recognize that `1.6.0` is Cats' version number.

**Comment by kiranbayram** [comment]
This issue should be closed i guess. @yannick-cw you can check the examples at [ExampleTest](https://github.com/fthomas/scala-steward/blob/master/modules/core/src/test/scala/org/scalasteward/core/model/ExampleTest.scala)

**Comment by yannick-cw** [comment]
@kiranbayram yes looks great :)
