### ISSUE TITLE
Add labels to pull requests

### ISSUE THREAD

**Issue by Fristi** [fthomas/scala-steward#404]
It would be nice to classify a pull request by adding

- Library update
- Sbt plugin update
- Test library update

Such that you could do automatic patch releases by using mergify (auto-merge) + rancher (auto-tag) + sbt-release-early. I would only release a new artifact if there is a Library update

**Comment by fthomas** [comment]
I like this idea. Customisation of the labels (or disabling/enabling this feature) could be configured via `.scala-steward.conf`.

**Comment by kiranbayram** [comment]
Hello there, are we talking about Github labels here? Push access seems to be required to add labels to issues (PRs are also issues in Github api context). That could be a problem.

**Comment by fthomas** [comment]
Yes, I assumed GitHub labels. An alternative could be to just add "labels" to the PR body as plain text like this: `labels: library-update`. Other tools might be able to work with such labels too.

**Comment by kiranbayram** [comment]
Putting labels into PR body as plain text should work, yes. I may give this a go in coming days if i get to have some free time.

**Comment by MPV** [comment]
I added #1471 as follow-up issue for adding GitHub labels, in case there's others interested in that feature.
