### ISSUE TITLE
Publish scala-steward docker image to registry?

### ISSUE THREAD

**Issue by anilkumarmyla** [fthomas/scala-steward#407]
I looked at https://hub.docker.com/ to find scala-steward docker image that can be used for private projects, failing to find any. Are there any plans of publishing scala-steward to docker registry?

**Comment by Slakah** [comment]
I would be happy to pick this up, it does feel like it would be quite useful. I'm currently maintaining a separate fork, which is used to build the docker image which is a bit of a pain.

**Comment by Daenyth** [comment]
Looks like it should be fairly straightforward if an account on docker hub is created: https://docs.travis-ci.com/user/build-stages/share-docker-image/

**Comment by Slakah** [comment]
I've raised a PR #681 , which should hopefully show a way to implement this.

**Comment by fthomas** [comment]
Fixed by #681.
