### ISSUE TITLE
Usage of println instead of logger

### ISSUE THREAD

**Issue by anilkumarmyla** [fthomas/scala-steward#420]
There are around 6 usages of println in the codebase instead of using logger. Just wondering if that's intended or we can switch to logger. Willing to help, let me know!

**Comment by mcanlas** [comment]
Not the author but doing it with a logger would be the More Right thing to do. I say go for it.

Maybe some of the code would need some refactoring to make stacking the logger easier (if modeled as a proper effect).

**Comment by fthomas** [comment]
println is used in parts of the code base where I experimented with ideas and expected to clean up after those ideas turned out to be useful. So if you see a println, the surrounding code's quality is not on par with the rest of the code base and will be refactored sooner than later.
