### ISSUE TITLE
Dependency names with backticks

### ISSUE THREAD

**Issue by kiranbayram** [fthomas/scala-steward#457]
While writing documentation about good/bad examples, I've noticed that dependency names with backticks are not identified
```
val `scala-js-jquery-version` = "0.9.3"
```

**Comment by fthomas** [comment]
This is surprising to me. Thanks for the report!

**Comment by fthomas** [comment]
I failed to reproduce this in #458. Do you have a test case that reproduces this bug?

**Comment by kiranbayram** [comment]
The dependency i posted above indeed doesn't work but it is because i separated scala and js like `scala-js`. I'll add a good example for backticks into the test i'm writing at the moment
