### ISSUE TITLE
Instructions on how to run manually for private project?

### ISSUE THREAD

**Issue by Daenyth** [fthomas/scala-steward#48]
I'd like to use this on my company's codebase to help save maintenance time. Is that possible?

**Comment by fthomas** [comment]
There is now a `Config` class that contains all the things one wants to change when running Scala steward.

**Comment by Philippus** [comment]
I tried this out. By default a fork is made of the project under the specified username, for our setup cloning and then raising the PR directly would be preferred.
I also got a `422 Unprocessable Entity` after the `Create PR`-step, not sure what could be the cause of that.

**Comment by fthomas** [comment]
Note that #148 changed how the GiHub password / access token is passed to Git. The configuration of a token file has been replaced by an askpass program that Git invokes to retrieve the password.

**Comment by fthomas** [comment]
#161 allows to pass configuration parameters as command-line options. So scala-steward does not need to be recompiled to change the configuration.

**Comment by nafg** [comment]
What about just running it on a local project on my laptop? Specifically the logic that modifies the .sbt files.

**Comment by fthomas** [comment]
scala-steward is not designed to run on single projects. I think the best option here would be to create some kind of sbt-steward plugin that shares the logic for modifying source files with scala-steward. If you'd like to work on this, I could create appropriate repos at https://github.com/scala-steward-org

**Comment by nafg** [comment]
How coupled is the code right now? If the code is refactored so that part
is easy to move out, I could see myself doing it one day...

**Comment by fthomas** [comment]
I'd say it is already easy to move that part out. All the logic that modifies source code is currently in `Update.replaceAllIn`.

**Comment by blast-hardcheese** [comment]
It seems as though
> create a file ~/.github/tokens/$myLogin with a GitHub access token for the user myLogin
is no longer required as well

**Comment by blast-hardcheese** [comment]
Ah, and the last issue was my `GITHUB_HOST` variable was incorrect (left off the `/v3/api` suffix). Everything is working great now, I'll open a PR with the alterations to the `docker run` command

**Comment by tjheslin1** [comment]
I believe I'm having the same issue. @blast-hardcheese looking forward to your README update!

**Comment by cchantep** [comment]
Hi, first thx for this great tool. I would be interested to understand how this would work with private repos, specially how would it fork?

**Comment by fthomas** [comment]
@cchantep You have two options.

1. Use a user with appropriate permissions to read and fork you repos.
1. Use a user that has permissions to create pull requests in your repos and run with `--do-not-fork` (#208) so that repos are not forked and pull requests are directly created in the target repositories.

**Comment by ChristopherDavenport** [comment]
We use a repo with a git submodule to avoid repo interactions.

**Comment by cchantep** [comment]
The @fthomas, second option seems fine for private enterprise repos.

**Comment by cchantep** [comment]
Have create a PR with some suggestion for the related documentation.

BTW is there any way/plan to support repository where SBT is not setup at the root of the repo?

**Comment by fthomas** [comment]
@cchantep #678 should also take care of repositories where the build is not in the root directory.

**Comment by fthomas** [comment]
Fixed by #683.
