### ISSUE TITLE
suggestion: don't suggest SNAP/SNAPSHOT versions unless I'm already on one

### ISSUE THREAD

**Issue by SethTisue** [fthomas/scala-steward#483]
I'm seeing this with ScalaTest a lot lately

e,.g. if I'm on 3.1.0-SNAP1, then a PR upgrading to 3.1.0-SNAP2 is helpful

but if I'm on 3.0.x, a PR upgrading to 3.1.0-SNAP2 is likelier to be annoying than helpful

real-world example of annoyed maintainer: https://github.com/scala/scala-swing/pull/106

**Comment by fthomas** [comment]
scala-steward inherits this behavior from sbt-updates. If I'm correct it will only suggest 3.1.0-SNAP2 as update of 3.0.x if x contains a hyphen, for example if x = 8-RC2 as it is the case in the linked PR. It won't suggest that update if x consists of digits only.

I agree that it is not helpful to suggest PRs that go from RC to SNAPSHOT versions. It should be easy for scala-steward to filter any update where the new version contains `SNAP` but the current version don't.

**Comment by fthomas** [comment]
Ok, I just merged #485 so these PRs should not happen anymore. And btw, thanks for the report Seth!

**Comment by SethTisue** [comment]
no problem, thanks for the prompt patch, that's awesome!
