### ISSUE TITLE
Promote use of Scala steward with a badge

### ISSUE THREAD

**Issue by ludovicc** [fthomas/scala-steward#491]
In Javascript world, projects using Greenkeeper to keep their dependencies up-to-date show a badge as in https://github.com/stencila/nixster

Promote the use of a similar badge for Scala steward.

**Comment by fthomas** [comment]
Good idea. Should be as easy as creating a badge on https://shields.io/ and adding some instructions to the README.

**Comment by exoego** [comment]
How about this badge ?
![Scala Steward badge](https://img.shields.io/badge/Scala_Steward-helping-green.svg?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAQCAMAAAARSr4IAAAAVFBMVEUAAACHjojlOy5NWlrKzcYRKjGFjIbp293YycuLa3pYY2LSqql4f3pCUFTgSjNodYRmcXUsPD/NTTbjRS+2jomhgnzNc223cGvZS0HaSD0XLjbaSjElhIr+AAAAAXRSTlMAQObYZgAAAHlJREFUCNdNyosOwyAIhWHAQS1Vt7a77/3fcxxdmv0xwmckutAR1nkm4ggbyEcg/wWmlGLDAA3oL50xi6fk5ffZ3E2E3QfZDCcCN2YtbEWZt+Drc6u6rlqv7Uk0LdKqqr5rk2UCRXOk0vmQKGfc94nOJyQjouF9H/wCc9gECEYfONoAAAAASUVORK5CYII=)
