### ISSUE TITLE
scala-steward attempts to upgrade to an nonexistent version

### ISSUE THREAD

**Issue by Atry** [fthomas/scala-steward#502]
In [this pull request](https://github.com/ThoughtWorksInc/Dsl.scala/pull/247/files#diff-6cc757018c544cd4102c01bf33798304R17), scala-steward attempt to upgrade from `1.2.0+14-7a373cbd` to `1.3.0+14-7a373cbd`, which is an nonexistent version.

**Comment by fthomas** [comment]
Thanks for the report @Atry. The diff looks good now because @scala-steward updated the PR in the meantime but the erroneous commit is still there: https://github.com/ThoughtWorksInc/Dsl.scala/commit/cb487d1b4cf5060210988d29c255627692519373
