### ISSUE TITLE
How to run scala-steward on kubernetes?

### ISSUE THREAD

**Issue by ghostbuster91** [fthomas/scala-steward#518]
It would be great if I could provide github credentials simply by value rather than by using askpassword script strategy.

My use case is following - I plan to run scala-stwerad on our internal infrastructure using docker. 

I though that I would create a repository with our own `repos.md` file and  a custom docker image based on scala-stewared docker image (which I hope will be published soon #407). which will contain our `repos.md` inside. Whenever this repository changes a new build will be triggered which will result in a new docker image being produced. Later I would deploy this image to the cloud.The cloud has already access to credentials so I could configure my own scala steward to use it (e.g. kuberenetes + secrets). But here is the problem - right now I have to bundle my github credentials into docker image which is not very good from security perspective.

What I would like is an option to pass this credentials using simple value.

Of course I could create some kind of storage based on credentials with this one file but that requires some work.

Edit: I found a workaround: inside askpass script put something like `echo $SECRET_TOKEN` and then later bind this global variable using your preferred method (can be done using kubernetes secrets).
Maybe it would be worth to add this as a tip to readme.

**Comment by fthomas** [comment]
scala-steward used to put the GitHub password into the clone URL which meant that it was stored in each clone in the `.git/config` file. It was later changed to the askpass mechanism in https://github.com/fthomas/scala-steward/pull/148 to prevent that. Passing the password by value to scala-steward (probably as command-line parameter) would again mean that it would end up in  `.git/config` files. From a security perspective I think using askpass mechanism is the best we can do right now although it is a little bit inconvenient.

**Comment by daddykotex** [comment]
@ghostbuster91 I've not yet tried it but I'm in a similar position. I run `scala-steward` on an internal Kubernetes cluster and I use the following settings:
* one config map for the `repos.md` (no need to rebuild the image every time)`
* one secret that contains the `askpass.sh`, with executable permissions
* one persistent volume so that the thing does not start from scratch every time

It works as-is out of the box ( plus I've added the gitlab support ;) ).

**Comment by ghostbuster91** [comment]
@ghostbuster91 Yes, my solution is very similar. I don't populate repos.md directly from config map, I prefer to store it in a github repository, this way it is easier for other developers. who does not know kubernetes well, to add new repos. I forgot that secrets can be mapped to volumes as well so I did this trick with environment variable inside `askpass.sh`, but basically it is the same. And obviously one pvc to cache some stuff.

**Comment by fthomas** [comment]
@ghostbuster91 @daddykotex Do you think this is worth documenting or should we just close this issue?

**Comment by ghostbuster91** [comment]
I see third option: Closing & renaming issue so it contains something about kubernetes in the title this way it will be easier to found this thread in the future

**Comment by fthomas** [comment]
Sounds good to me. Feel free to rename and close it.

**Comment by daddykotex** [comment]
Thank you @ghostbuster91

**Comment by MPV** [comment]
You could also use/take a look at what @MaT1g3R has done here:
https://github.com/GarnerCorp/charts/tree/master/charts/scala-steward

**Comment by MPV** [comment]
Maybe that could potentially be moved into the [scala-steward-org](https://github.com/scala-steward-org/) organisation, what do you think? 

I asked the equivalent question over in https://github.com/GarnerCorp/charts/issues/3 too.
