### ISSUE TITLE
Bitbucket support

### ISSUE THREAD

**Issue by intracer** [fthomas/scala-steward#562]
Same motivation as GitLab support #313.
Also to track already ongoing efforts in https://github.com/fthomas/scala-steward/compare/master...tjheslin1:bitbucket

**Comment by dpfeiffer** [comment]
As I could see from the discussion in #313 the GitLab work has been based on @tjheslin1 work for Bitbucket. A colleague and I are giving it a try today to base the actual implementation for Bitbucket on @daddykotex work and see how far we will come.

**Comment by tjheslin1** [comment]
@dpfeiffer Jolly good! Great news. Unfortunately I wasn't able to dedicate more time after my initial start at the problem! @daddykotex has done an excellent job!

**Comment by dpfeiffer** [comment]
@fthomas How do you like to proceed on integrating the generalization of the VCS? While working on this ticket, we encountered that some abstractions (that are tied towards the GitHub API) need to be reworked slightly to be more general and work as well with the Bitbucket API. Before we start to polish the code that we created on Friday it would be great to sort this out. Next week I will give it a try at work.

**Comment by fthomas** [comment]
@dpfeiffer I think it makes the most sense to base your work on the `topic/gitlab` branch which contains the GitLab support from @daddykotex from #524. That branch already has generalizations for GitHub's and GitLab's API.

**Comment by dpfeiffer** [comment]
@fthomas I based it directly on @daddykotex `refactor/vcsalg` which is the one you integrated into `topic/gitlab`, right?

I finished a rough implementation yesterday which i would like to evaluate internally first (first trial runs seemed to work fine) and of course polish (https://github.com/fthomas/scala-steward/compare/topic/gitlab...dpfeiffer:topic/bitbucket)
