### ISSUE TITLE
Idea: After a batch of dependency updates, trigger a automated minor release?

### ISSUE THREAD

**Issue by Fristi** [fthomas/scala-steward#6]
Could we do that?

To identify the batch we could label all pull requests made by the bot by the current build number.
If all were successful and merged we could trigger somehow a release?

Challenges
- What if new features were introduced? Should we check the commits as well if they are only dependency update commits?
- A changelog should also be updated, this also ( needs to | could ) be automated

**Comment by Fristi** [comment]
I think this is outside the scope of the project? Maybe this can be done with other tools

**Comment by fthomas** [comment]
My focus so far was and still is to improve the dependency updates and to make it usable for a large number of projects. And there is still a lot to do in this area. But I also remain open to add additional functionality to scala-steward that helps maintaining Scala projects.
