### ISSUE TITLE
Better title for dependencies whose name is part of the groupId

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#60]
See https://github.com/pdalpra/gh4s/pull/15 for an example.

**Comment by fthomas** [comment]
That would be great, @bhop! I would start with a test that reproduces the current behaviour. The title is built with a call to `Update.Group("com.softwaremill.sttp", Nel.of("circe", "core", "okhttp-backend-monix"), "1.3.3", Nel.of("1.3.5")).name` which currently just returns `"circe"`. If `name` could be changed such that it would return `sttp`, `sttp:core`, or `sttp:circe` (or something else that contains `sttp`) that would produce a much better title.

**Comment by bhop** [comment]
Thanks @fthomas!
Maybe for Group update we can return something like: `sttp:circe, sttp:core, sttp:okhttp-backend-monix`. What do you think?

**Comment by fthomas** [comment]
We can do this but we should make sure that the title does not get too long.

**Comment by bhop** [comment]
Agree, we can take first three artifacts and if there is more we can put `...` at the end

**Comment by Fixifaer87** [comment]
Ok
