### ISSUE TITLE
Change groupId when dependencies publish under a different groupId

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#613]
Sometimes dependencies start publishing under a different `groupId` when maintainers change or the maintainers want to extend the pool of people able to publish new releases. One recent example is the [kind-projector](https://github.com/typelevel/kind-projector) project which was moved to the Typelevel organization:
 ```
"org.spire-math" %% "kind-projector" % "0.9.10" ->
"org.typelevel"  %% "kind-projector" % "0.10.0"
```
It would be nice if Scala Steward would also change the `groupId` in this instance. Currently this needs to be done manually.

@Philippus proposed this feature at Scala Days in Lausanne.

**Comment by kubukoz** [comment]
This would have to be configured in scala-steward itself, right? There's no way it could find out about that from sbt-updates (the only possible place would probably be the source github repo of the dependency, if it kept track of that one).

**Comment by fthomas** [comment]
Yes, I think there would be a manually maintained list of updates that change the `groupId in Scala Steward. At least I'm not aware of a way to determine this kind of change automatically.
