### ISSUE TITLE
Update PRs if there's another one updating to a previous version

### ISSUE THREAD

**Issue by adamw** [fthomas/scala-steward#618]
Some libraries are updated very often, e.g. `aws-java-sdk`. This means a lot of PRs are opened (almost every day). Would be great if the old PRs could be updated (or closed) when there's a new version, and the previous update hasn't been merged yet.

Example: https://github.com/softwaremill/elasticmq/pulls

**Comment by fthomas** [comment]
This is a duplicate of #418 and #119.

An interim solution could be to ignore all updates of these dependencies via `.scala-steward.conf`.

**Comment by plokhotnyuk** [comment]
Can it be configured to skip only patch versions or according to some pattern?

**Comment by adamw** [comment]
@fthomas Ah, sorry! closing then and subscribing to the other ones

**Comment by fthomas** [comment]
@plokhotnyuk Yes, I think it can. If I remember correctly the following configuration for example would prevent any updates for sbt-native-packager 1.3.x but would create PRs for 1.4.x and any other version that does not start with `1.3.`:
```
updates.ignore = [{ groupId = "com.typesafe.sbt", artifactId = "sbt-native-packager", version = "1.3." }]
```

@adamw No problem!
