### ISSUE TITLE
Update scalafmt version

### ISSUE THREAD

**Issue by 2m** [fthomas/scala-steward#625]
scalafmt gets its version from the `.scalafmt.conf` file, like here:

https://github.com/akka/alpakka/blob/06f323f9b2940a18fc6dd63d5127715847341e01/.scalafmt.conf#L1

It would be awesome if scala-steward could upgrade that when a new scalafmt version comes out.

**Comment by fthomas** [comment]
:+1:

My guess is that if we have the ability to update the sbt version (https://github.com/fthomas/scala-steward/issues/101), updating the scalafmt version could be done in a similar fashion.
