### ISSUE TITLE
Support published Scalafix rules

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#629]
As described in https://scalacenter.github.io/scalafix/docs/users/installation.html#run-custom-rules. Supporting rules that need to be added via `scalafixDependencies` would only require an additional sbt file before running the rule.

**Comment by mzuehlke** [comment]
Published rules can be specified using the `dependency:` prefix. E.g.
```
dependency:PlayWS@com.github.xuwei-k:play-ws-scalafix:0.1.0
```

See: https://scalacenter.github.io/scalafix/docs/rules/external-rules.html

**Comment by fthomas** [comment]
Nice! So there is nothing to be done in Scala Steward to also support published Scalafix rules in our Scalafix migrations feature, right? Just use a `dependency:` rule in the `rewriteRules` field in [`scalafix-migrations.conf`](https://github.com/fthomas/scala-steward/blob/85dfbfb5a23dba29b093a7f5d5f55a30dbee72be/modules/core/src/main/resources/scalafix-migrations.conf) and that's it.

**Comment by mzuehlke** [comment]
I will make a PR to add this (and the change from #1442 ) to the [documentation](https://github.com/fthomas/scala-steward/blob/master/docs/scalafix-migrations.md)
