### ISSUE TITLE
False update message regarding sbt

### ISSUE THREAD

**Issue by exoego** [fthomas/scala-steward#679]
See 
- https://github.com/larsrh/sbt-libisabelle/pull/14
- https://github.com/raboof/sbt-reproducible-builds/pull/111/files

The diff shows only in build.properties, but sbt plugin are shown in title and description.

**Comment by fthomas** [comment]
sbt-libisabelle has this in `project/plugins.sbt`:
```sbt
libraryDependencies += "org.scala-sbt" %% "scripted-plugin" % sbtVersion.value
```
and sbt-reproducible-builds has this in `project/scripted.sbt`:
```sbt
libraryDependencies += { "org.scala-sbt" %% "scripted-plugin" % sbtVersion.value }
```
I would argue that the update message is therefore correct in both cases.

**Comment by exoego** [comment]
Ah, i overlooked.
