### ISSUE TITLE
Errors when using --do-not-fork with repos owned by groups on GitLab

### ISSUE THREAD

**Issue by yaroot** [fthomas/scala-steward#689]
There is no `owner` field for repos owned by a group, I [made](https://github.com/yaroot/scala-steward/commit/b88e18a1793ca6609659c00cfc7ea71b7a0630ec) a quick & dirty fix to read _namespace/name_ if _name_ field failed to decode, but I don't think this is a good solution.

ping @daddykotex

**Comment by daddykotex** [comment]
I've never tested `--do-not-fork` but it seems to me that this would be the correct fix

**Comment by tyrcho** [comment]
I had the same issue, would be glad to see this fixed !

**Comment by tyrcho** [comment]
I've tested your version @yaroot and it seems to work. I have other issues but they don't seem related to the owner property.

**Comment by daddykotex** [comment]
My pull requests addresses the 404 you are seeing: https://github.com/fthomas/scala-steward/pull/738

**Comment by tyrcho** [comment]
@yaroot I think this has been fixed with the latest changes in master. At least on my side I don't have the issue anymore.
