### ISSUE TITLE
Publish docker images for the past releases

### ISSUE THREAD

**Issue by tanishiking** [fthomas/scala-steward#782]
Big thanks to https://github.com/fthomas/scala-steward/pull/681, now the [docker image for scala-steward](https://hub.docker.com/r/fthomas/scala-steward) is available from docker hub :tada:
Though the `.travis.yml` is designed to publish the docker images triggered by new commits to `master` or new release, docker images for past stable releases (e.g., for 0.3.0) are not available (because https://github.com/fthomas/scala-steward/pull/681 was merged quite recently).

It would be helpful if the docker image for (at least 0.3.0) is available.
Thanks anyway for maintaining this fantastic bot!

**Comment by fthomas** [comment]
I briefly tried to publish an image for 0.3.0 from my local dev environment, but that failed. I'm afraid you'll have to wait until 0.4.0 for a docker image of a released version. Since there already have been a lot of changes since the last release, the 0.4.0 release will happen in the near future.

**Comment by tanishiking** [comment]
Thank you so much for trying to do that :)

> the 0.4.0 release will happen in the near future.

Perfect! It may be a good idea to wait until 0.4.0 because, as you said, there are a lot of great improvements there. Until then I'll use the image that is tagged with `latest` 👍 
Closing for now.
