### ISSUE TITLE
Link to diff of changes for GitHub projects

### ISSUE THREAD

**Issue by cb372** [fthomas/scala-steward#794]
Once #762 has been merged, I think a nice enhancement would be to link to a GitHub URL showing the changes, e.g. `https://github.com/typelevel/cats/compare/v2.0.0-M4...v2.0.0-RC1`

The logic would be something like:

1. Grab a list of the tags from GitHub (if the dependency is a public repo)?
2. Try to match the old and new version numbers to tag names. This could be really naive, e.g. version is `2.0.0-M4` so assume the tag name is `v2.0.0-M4`, or something a bit more sophisticated
3. Somehow validate whether the generated URL is valid? For public repos, this could be done by hitting the URL and checking it's not a 404.

Obviously there's quite a lot that can go wrong here, so this would be very much a "best effort" thing. If anything went wrong, we wouldn't display the link.

**Comment by fthomas** [comment]
This is a cool idea!
