### ISSUE TITLE
Include a link to the upgraded project in the PR

### ISSUE THREAD

**Issue by ennru** [fthomas/scala-steward#82]
... in a perfect world to its release notes.

**Comment by fthomas** [comment]
Good idea, @ennru. Do you have an idea how to obtain the URL of the website or the release notes from maven coordinates (*groupId*,*artifactId*, and a version) because currently that is the only thing the bot knows about a dependency. Any suggestions are welcome.

**Comment by SethTisue** [comment]
I think you'd have to use Scaladex as your information source, Scaladex knows this kind of thing

**Comment by ennru** [comment]
Do you have access to the `pom.xml`? If the SCM section points to Github, you could point to the *Releases* tab.

**Comment by fthomas** [comment]
sbt-updates does not download the `pom.xml` but only the `maven-metadata.xml` which just contains the versions. But I could fetch the `pom.xml` with coursier via `coursier fetch -A pom $groupId:$artifactId:$version`. This should work for all public dependencies.

**Comment by mwz** [comment]
It would be great if scala-steward could include release notes in the description of the PR, similarly to how dependabot does it - see the screenshot below for a reference:

![Screenshot 2019-07-03 at 16 39 29](https://user-images.githubusercontent.com/1190768/60605313-370ecd80-9db1-11e9-949f-c754cc09793f.png)

This data is fetched from Github releases, so we could use it for projects which use this feature and provide any release notes. This feature would be quite cool, I'd be happy to contribute this if that's something you would be keen on having in scala-steward, @fthomas.

**Comment by fthomas** [comment]
That would be awesome, @mwz!
