### ISSUE TITLE
Organization change didn't work

### ISSUE THREAD

**Issue by kubukoz** [fthomas/scala-steward#858]
It seems like https://github.com/kubukoz/brick-store didn't get the update for kind-projector, which should've happened since #619. I'll try to see why, but maybe you have some ideas...

**Comment by fthomas** [comment]
Organization changes are currently not taken into account when Scala Steward looks for repos that it needs to work on. Eventually, the PR was created a few days later (https://github.com/kubukoz/brick-store/pull/59) when Scala Steward worked on brick-store because another dependency was outdated.

**Comment by fthomas** [comment]
Btw, I think this will be fixed by #851.
