### ISSUE TITLE
Attempt to upgrade to cats-effect 2.0.0-RC2

### ISSUE THREAD

**Issue by julien-truffaut** [fthomas/scala-steward#864]
Hi all,

I just got a PR to upgrade cats module to 2.0.0-RC2 but it also tried to upgrade cats-effect to 2.0.0-RC2 (which does not exist).

https://github.com/fp-tower/foundation/pull/77/commits/1c4630320b79894680bd1802ac839f2c35dadc8a

It is not a big deal but I imagine it illustrates a bug in the version upgrade. Thanks!

**Comment by fthomas** [comment]
Yes, this is a bug. I've observed the same problem in #793. Fortunately the fix for this should be straightforward.
