### ISSUE TITLE
Configure version ranges (e.g binary compatibility)

### ISSUE THREAD

**Issue by dwijnand** [fthomas/scala-steward#91]
Are there facilities in scala-steward to configure version ranges?

For example https://github.com/lightbend/ssl-config/pull/133 updates joda-time from 2.9.9 to 2.10.  Now, leaving aside that right this moment I don't know if that's a safe update for ssl-config, assuming we can't do that upgrade how do I inform scala-steward that for the moment we want only updates in the 2.9.x version series?

(Thanks for the bot, looks like a great addition to the ecosystem!)

**Comment by fthomas** [comment]
There is no way to do this right now, but this is very reasonable feature request. I think that the same configuration mechanism could also be used to ignore whole dependencies independent of the current or next version (e.g. https://github.com/scala/scala-dist/pull/194#issuecomment-429425051).

In a first step I think it would make sense to configure this in some kind of `.scala-steward.conf` config file in the root directory of a repo which could contain a list of regular expressions. If an update matches one of the regexes Scala steward could just ignore it.

**Comment by dwijnand** [comment]
Sounds reasonable to me!

**Comment by fthomas** [comment]
There is now a [provisional mechanism](https://github.com/fthomas/scala-steward/blob/8a6bd26b97d09e943412b56975d11fb7bd1ca2cc/modules/core/src/main/scala/eu/timepit/scalasteward/update/FilterAlg.scala) to ignore updates globally or per repo which we can use until this feature is properly implemented.

**Comment by fthomas** [comment]
There is now a PR (#301) which makes this possible via a repo-provided `.scala-steward.conf` that contains
```
allowedUpdates: [ { groupId: "joda-time", artifactId: "joda-time", version: "2.9." } ]
```
With this scala-steward would only create PRs for joda-time updates where the new version starts with `2.9.`.

**Comment by dwijnand** [comment]
I've since learn that you can respond to @dependabot PRs telling it to ignore version series.  Something to look into :)
