### ISSUE TITLE
Incorrect diff for sbt update

### ISSUE THREAD

**Issue by eed3si9n** [fthomas/scala-steward#92]
## steps

https://github.com/lightbend/paradox/pull/268

```diff
- addSbtPlugin("com.geirsson"          % "sbt-ci-release"  % "1.2.1")
+ addSbtPlugin("com.geirsson"          % "sbt-ci-release"  % "1.2.5")
```

## problem

Not sure why sbt-ci-release change was made here.

## expectation

sbt version update should be done using `project/build.properties`.

**Comment by fthomas** [comment]
Thanks for the report, @eed3si9n! This shouldn't happen again.
