### ISSUE TITLE
Move repos.md file into different repository

### ISSUE THREAD

**Issue by fthomas** [fthomas/scala-steward#979]
The repos.md file in this repository is getting bigger by the day and PRs that modify it distract from the changes in Scala Steward itself. I'd therefore propose to move it to a new repository that only contains this one file.

**Comment by exoego** [comment]
I agree.
It reduces notifications for repo watchers and let us focus in bugs/enhancements.

**Comment by fthomas** [comment]
I just extracted `repos.md` from this repo with
```
git clone https://github.com/fthomas/scala-steward.git
cd scala-steward
git filter-branch -f --prune-empty --index-filter 'git rm --cached --ignore-unmatch $(git ls-files | grep -v "repos.md")'
```
and pushed it to https://github.com/scala-steward-org/repos.
