### ISSUE TITLE
Update changelog along with dependency

### ISSUE THREAD

**Issue by tomasherman** [fthomas/scala-steward#993]
Hi,

thanks for a extremely useful service. It could be even better, though :) I would love for scala steward to automatically make a note about what it did into changelog. The idea is you could configure file in a repo and inside it put a line with some place holder values like `{scala-steward-original-version}` and `{scala-steward-updated-version}` and when SS creates PR, it not just updates build.sbt, but also copies this line and into one of those copies puts actual values.

What do you think?
Thanks!

**Comment by fthomas** [comment]
Thanks for the suggestion, @tomasherman! I feel that tools that are specialized for creating release notes or changelogs from issues or PRs like [gren](https://github.com/github-tools/github-release-notes) or [release-drafter](https://github.com/toolmantim/release-drafter) are better suited to do this task. I'm reluctant to include features that are somewhat orthogonal to what Scala Steward does or which are not Scala specific.

**Comment by tomasherman** [comment]
ok, fair enough ;)
